import { SignInButton, SignOutButton, useUser } from '@clerk/nextjs';
import Head from 'next/head';

export default function Home() {
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to the App</h1>
      {!user.isSignedIn && <SignInButton>Sign in with GitHub</SignInButton>}
      {user.isSignedIn && <SignOutButton>Sign Out</SignOutButton>}
    </>
  );
}
